repos:
  # - repo: https://github.com/hhatto/autopep8
  #   rev: 'v2.0.4'  # Use the tag you prefer
  #   hooks:
  #     - id: autopep8
  #       args: ['--in-place']
  - repo: https://github.com/pycqa/flake8
    rev: '6.1.0'  # Use the latest commit on the master branch
    hooks:
      - id: flake8
        args: ['--ignore=E501,F401,W503']
  - repo: https://github.com/psf/black
    rev: '23.11.0'  # Use the latest commit on the master branch
    hooks:
      - id: black
        args: ['dino']
  - repo: https://github.com/kynan/nbstripout
    rev: '0.6.0'  # Use a specific version of nbstripout
    hooks:
      - id: nbstripout
  # - repo: https://github.com/pycqa/pylint
  #   rev: ''  # Use the latest commit on the master branch
  #   hooks:
  #     - id: pylint
  #       args: ['--exit-zero', 'dino']
