data:
  query_dataset_path: KNN:root=/root/data:split=query:subset=fold_0
  test_dataset_path: KNN:root=/root/data:split=test:subset=fold_0

output_dir: 'output'
experiment_name: 'eval'

batch_size_per_gpu: 256

nb_knn: 20
temperature: 0.07
save_features: false

student:
  arch: vit_small
  patch_size: 16
  pretrained_weights: ''
  checkpoint_key: 'teacher'

speed:
  use_cuda: true
  num_workers: 16

wandb:
  enable: true
  project: 'vision'
  username: 'vlfm'
  exp_name: 'eval'
  tags: ['${experiment_name}', 'knn', '${student.arch}']
  dir: '/home/user'
  group:
  to_log:
  resume_id: